payload:
  - DOMAIN-KEYWORD,grazie.ai
  - DOMAIN-KEYWORD,grazie.aws.intellij.net
  - DOMAIN-KEYWORD,openai
  - DOMAIN-SUFFIX,anyproxy.io
  - DOMAIN-SUFFIX,bito.ai
  - DOMAIN-SUFFIX,apache.org
  - DOMAIN-SUFFIX,hutao.cloud
  - DOMAIN-SUFFIX,psv4.userapi.com
  - DOMAIN-SUFFIX,unity3d.com
  - DOMAIN-SUFFIX,olevod.com
  - DOMAIN-SUFFIX,unity.com
  - DOMAIN-SUFFIX,cache-redirector.jetbrains.com
  - DOMAIN-SUFFIX,postman.com
  - DOMAIN-SUFFIX,paofu.cloud
  - DOMAIN-SUFFIX,stackoverflow.com
  - DOMAIN-SUFFIX,developer.chrome.com
  - DOMAIN-SUFFIX,go.dev
  - DOMAIN-SUFFIX,download.eclipse.org
  - DOMAIN-SUFFIX,postman.co
  - DOMAIN-SUFFIX,figma.com
  - DOMAIN-SUFFIX,maven.org
  - DOMAIN-SUFFIX,mozilla.org
  - DOMAIN-SUFFIX,mozilla.net
  - DOMAIN-SUFFIX,registry.yarnpkg.com
  - DOMAIN-SUFFIX,registry.npmjs.org
  - DOMAIN-SUFFIX,cxyzjd.com
  - DOMAIN-SUFFIX,dandanzan.com
  - DOMAIN-SUFFIX,chromium.org
  - DOMAIN-SUFFIX,wallhaven.cc
  - DOMAIN-SUFFIX,github.io
  - DOMAIN-SUFFIX,leetcode.com
  - DOMAIN-SUFFIX,videojs.com
  - DOMAIN-SUFFIX,freedownloadmanager.org
  - DOMAIN-SUFFIX,qdownloader.net
  - DOMAIN-SUFFIX,limbopro.xyz
  - DOMAIN-SUFFIX,shadowsocks.com
  - DOMAIN-KEYWORD,gitbook
  - DOMAIN-KEYWORD,github
  - IP-CIDR,13.250.177.223/32